# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go get .
      - name: Build for Linux and Windows and Macos
        run: |
          cd examples/server/cmd/server
          CGO_ENABLED=0 go build -trimpath -ldflags "-s -w -extldflags '-static'" -tags "with_extend,with_ai,with_ci,with_iot,with_etl" -v -o rulego-server-all-linux-amd64
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-s -w -extldflags '-static'" -tags "with_extend,with_ai,with_ci,with_iot,with_etl" -v -o rulego-server-all-windows-amd64.exe
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags "-s -w -extldflags '-static'" -tags "with_extend,with_ai,with_ci,with_iot,with_etl" -v -o rulego-server-all-macos-amd64
          CGO_ENABLED=0 GOARCH=arm64 go build -trimpath -ldflags "-s -w -extldflags '-static'" -tags "with_extend,with_ai,with_ci,with_iot,with_etl" -v -o rulego-server-all-linux-arm64
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags "-s -w -extldflags '-static'" -tags "with_extend,with_ai,with_ci,with_iot,with_etl" -v -o rulego-server-all-macos-arm64
          CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -trimpath -ldflags "-s -w -extldflags '-static'" -tags "with_extend,with_ai,with_ci,with_iot,with_etl" -v -o rulego-server-all-windows-arm64.exe
          CGO_ENABLED=0 go build -trimpath -ldflags "-s -w -extldflags '-static'" -v -o rulego-server-linux-amd64
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-s -w -extldflags '-static'" -v -o rulego-server-windows-amd64.exe
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags "-s -w -extldflags '-static'" -v -o rulego-server-macos-amd64
          CGO_ENABLED=0 GOARCH=arm64 go build -trimpath -ldflags "-s -w -extldflags '-static'" -v -o rulego-server-linux-arm64
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags "-s -w -extldflags '-static'" -v -o rulego-server-macos-arm64
          CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -trimpath -ldflags "-s -w -extldflags '-static'" -v -o rulego-server-windows-arm64.exe
          CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -trimpath -ldflags "-s -w -extldflags '-static'" -tags "with_extend,with_iot" -v -o rulego-server-all-linux-386
          CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -trimpath -ldflags "-s -w -extldflags '-static'" -v -o rulego-server-linux-386
      - name: Create compressed archives
        run: |
          cd examples/server/cmd/server
          # 为每个二进制文件创建单独的压缩包
          # 带有所有扩展的版本
          tar -czf rulego-server-all-linux-amd64.tar.gz rulego-server-all-linux-amd64
          zip rulego-server-all-windows-amd64.zip rulego-server-all-windows-amd64.exe
          tar -czf rulego-server-all-macos-amd64.tar.gz rulego-server-all-macos-amd64
          tar -czf rulego-server-all-linux-arm64.tar.gz rulego-server-all-linux-arm64
          tar -czf rulego-server-all-macos-arm64.tar.gz rulego-server-all-macos-arm64
          zip rulego-server-all-windows-arm64.zip rulego-server-all-windows-arm64.exe
          tar -czf rulego-server-all-linux-386.tar.gz rulego-server-all-linux-386
          
          # 基础版本
          tar -czf rulego-server-linux-amd64.tar.gz rulego-server-linux-amd64
          zip rulego-server-windows-amd64.zip rulego-server-windows-amd64.exe
          tar -czf rulego-server-macos-amd64.tar.gz rulego-server-macos-amd64
          tar -czf rulego-server-linux-arm64.tar.gz rulego-server-linux-arm64
          tar -czf rulego-server-macos-arm64.tar.gz rulego-server-macos-arm64
          zip rulego-server-windows-arm64.zip rulego-server-windows-arm64.exe
          tar -czf rulego-server-linux-386.tar.gz rulego-server-linux-386
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rulego-server-compressed
          path: |
            examples/server/cmd/server/*.tar.gz
            examples/server/cmd/server/*.zip
#      - name: Create Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: ${{ github.event.head_commit.message }}
#          draft: false
#          prerelease: false
